server:
  port: 8761

spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF