server:
  port: 9000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-routing
          uri: http://localhost:9001
          predicates:
            - Path=/**
          filters:
            - name: CircuitBreaker
              args:
                name: hystrix
                fallbackuri: forward:/userServiceFallback

jwt:
  secret: jwt-sample-secret

hystrix:
  command:
    fallbackcmd:
      execution:
        isolaton:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost