server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ramazansakin/GeTaxiApp-Config-Repo
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

health:
  config:
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost